project:
  type: book
  output-dir: docs

book:
  title: "CODA para estudios del microbioma Seminario del proyecto METACIRCLE"
  author: "Grupo BIOCOM"
  date: "8-9 Junio 2023"
  
  chapters:
    - index.qmd
    - coda_7_6_203.qmd

bibliography: references.bib

format:
  html:
    theme: Journal
  pdf:
    documentclass: scrreprt

editor: visual

